### ISSUE TITLE
Hero list iteration incident

### ISSUE THREAD

**Issue by Misiogrzanka** [ArgentumHeart/WC3RPGLoader#2]
Probably a quick fix, but that's what we get.

![image](https://github.com/ArgentumHeart/WC3RPGLoader/assets/77200161/19d6553a-0137-419e-b34e-cc5d792fe4f4)

**Comment by Misiogrzanka** [comment]
Will probably be the same with Stargazer but don't have it so dunno.

**Comment by ArgentumHeart** [comment]
Fixed in the commit above. It will be included in next release! ^_^
